theme: jekyll-theme-slate 
name: OLAP PivotTable Extensions
title: OLAP PivotTable Extensions
description: An Excel add-in which extends the functionality of PivotTables on Analysis Services cubes and of the Excel Data Model (Power Pivot)
show_downloads: true
latest_download_url: "https://github.com/OlapPivotTableExtensions/OlapPivotTableExtensions/releases/download/v0.9.0/OLAP.PivotTable.Extensions.Setup.v0.9.0.exe"